apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fast-agent
  namespace: fast-system
  labels:
    app: fast-agent
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fast-agent
  template:
    metadata:
      labels:
        app: fast-agent
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      containers:
        - image: fishpro3/fast/fast-agent:latest
          imagePullPolicy: IfNotPresent
          name: fast-agent
          command:
            - /bin/fast-agent
            - --v=4
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 200Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/proc
              name: host-proc
            - mountPath: /host/var/run
              name: host-var-run
              mountPropagation: Bidirectional
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: fast-agent
      serviceAccountName: fast-agent
      volumes:
        - hostPath:
            path: /var/run
          name: host-var-run
        - hostPath:
            path: /proc
          name: host-proc
