apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fast-agent
  namespace: fast-system
  labels:
    app: fast-agent
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fast-agent
  template:
    metadata:
      labels:
        app: fast-agent
    spec:
      tolerations:
        - operator: Exists
      hostNetwork: true
      containers:
        - image: fishpro3/fast/fast-agent:latest
          imagePullPolicy: IfNotPresent
          name: fast-agent
          command:
            - /app/fast-agent
            - --v=6
          ports:
            - containerPort: 50051
              hostPort: 50051
              name: agent
              protocol: TCP
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 200Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/proc/sys/net
              name: host-proc-sys-net
            - mountPath: /host/proc/sys/kernel
              name: host-proc-sys-kernel
            - mountPath: /sys/fs/bpf
              mountPropagation: HostToContainer
              name: bpf-maps
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /tmp
              name: tmp
      nodeSelector:
        kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: fast-agent
      serviceAccountName: fast-agent
      volumes:
        - emptyDir: {}
          name: tmp
        - hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
          name: bpf-maps
        - hostPath:
            path: /lib/modules
            type: ""
          name: lib-modules
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
        - hostPath:
            path: /proc/sys/net
            type: Directory
          name: host-proc-sys-net
        - hostPath:
            path: /proc/sys/kernel
            type: Directory
          name: host-proc-sys-kernel

