apiVersion: v1
kind: ServiceAccount
metadata:
  name: fast-agent
  namespace: fast-system
  labels:
    app: fast
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fast-controller-manager
  namespace: fast-system
  labels:
    app: fast