name: GolangCI Lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - pkg
          - cmd
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: ${{matrix.working-directory}}
